# name=str(input("Enter your name:  "))
# age=int(input("Enter your age:  "))
# print("*******************************")
# print("Assalam u alaikum", name)
# print (f"you are {age} years old")
# print ("Welcome to python automation ")
# print("*******************************")

# name=input("Enter yout name:  ")
# age=int(input("Enter your Age:  "))
# city=input("Enter your City:  ")
# print("***************************")
# print("Name:  ",name)
# print("Age:   ", age)
# print("City:  ", city)
# print("Welcome to Python Automation!")
# print("***************************")

name=input("Enter yout name:  ")
age=int(input("Enter your Age:  "))
city=input("Enter your City:  ")
university=input("Enter your university name:  ")
semester=int(input("Enter semster:  "))
print("***************************")
print("Name:  ",name)
print("Age:   ", age)
print("City:  ", city)
print("University: ",university)
print("Semester:   ",semester)
print("Welcome to Python Automation!")

print("***************************")